name: deploy-document

on:
  workflow_run:
    workflows:
      - test
    branches:
      - main
    paths:
      - packages/**
    types:
      - completed

jobs:
  deploy-document:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    env:
      working-directory: ./documents/cheeket-document
    strategy:
      matrix:
        node-version: [ 16 ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.working-directory }}
      - name: Build website
        run: npm run build
        working-directory: ${{ env.working-directory }}
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        run:
          GIT_USER=${{ github.actor }} npm run deploy
        working-directory: ${{ env.working-directory }}
